version: "3.7"
services:
    php:
        image: ghcr.io/peon-dev/php:recipes-main
        volumes:
            - .:/peon
        working_dir: /peon
        depends_on:
            - composer

    # Helper service to keep composer depencencies up to date
    composer:
        image: ghcr.io/peon-dev/php:recipes-main
        volumes:
            - .:/peon
        working_dir: /peon
        entrypoint: "composer"
        command: [ "install", "--no-interaction" ]
