name: Tests

on:
    push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: 8.1
            coverage: none # default is xdebug
            extensions: mbstring # needed by phpunit

      -   run: composer install --dev --no-progress
      -   run: vendor/bin/phpunit


  phpstan:
      runs-on: ubuntu-latest
      steps:
        -   uses: actions/checkout@v2
        -   uses: shivammathur/setup-php@v2
            with:
              php-version: 8.1
              coverage: none # default is xdebug
              extensions: mbstring # needed by phpunit

        -   run: composer install --dev --no-progress

        -   run: composer run-script phpstan
